# Generated by Django 4.1.7 on 2023-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('observer_id', models.IntegerField(blank=True, null=True)),
                ('species_id', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Observations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observers',
            fields=[
                ('observer_id', models.AutoField(primary_key=True, serialize=False)),
                ('observer_name', models.TextField(blank=True, null=True)),
                ('observer_email', models.TextField(blank=True, null=True)),
                ('observation_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Observers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Russianbirds',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.TextField()),
                ('genus_name', models.TextField(blank=True, null=True)),
                ('latin', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('observation_number', models.IntegerField(blank=True, null=True)),
                ('aka', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RussianBirds',
                'managed': False,
            },
        ),
    ]
