# Generated by Django 4.1.7 on 2023-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Russianbirds',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.TextField()),
                ('genus_name', models.TextField(blank=True, null=True)),
                ('latin', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('observer', models.TextField(blank=True, null=True)),
                ('observation_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RussianBirds',
                'managed': False,
            },
        ),
    ]
