# Generated by Django 4.1.7 on 2023-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('amount', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('expense_date', models.TextField(blank=True, null=True)),
                ('added_date', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
