# Generated by Django 4.1.7 on 2023-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='russianbirds',
            options={},
        ),
    ]
