# Generated by Django 4.1.7 on 2023-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_maths', '0002_alter_russianbirds_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='russianbirds',
            name='observer',
        ),
        migrations.AddField(
            model_name='russianbirds',
            name='aka',
            field=models.TextField(null=True),
        ),
    ]
